id: AE8F8F8B0
title: f9947
type: translation
source_metadata:
  languages:
  - sa
  - en
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 16:41:32.073798
  last_modified_at: 2022-05-27 16:41:32.073800
